name: release cd
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'
  # workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # could not compile on ubuntu due to openssl, wayland
          # - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu       , use-cross: false , extension: ""   }
          # - { os: ubuntu-latest , target: x86_64-unknown-linux-musl      , use-cross: true  , extension: ""   }
          # - { os: ubuntu-latest , target: armv7-unknown-linux-gnueabihf  , use-cross: true  , extension: ""   }
          # - { os: ubuntu-latest , target: armv7-unknown-linux-musleabihf , use-cross: true  , extension: ""   }
          # - { os: ubuntu-latest , target: aarch64-unknown-linux-gnu      , use-cross: true  , extension: ""   }
          # - { os: ubuntu-latest , target: aarch64-unknown-linux-musl     , use-cross: true  , extension: ""   }
          - { os: macos-latest   , target: x86_64-apple-darwin            , use-cross: false , extension: ""   }
          - { os: macos-latest   , target: aarch64-apple-darwin           , use-cross: false , extension: ""   }
          - { os: windows-latest , target: x86_64-pc-windows-msvc         , use-cross: false , extension: .exe }
          - { os: windows-latest , target: aarch64-pc-windows-msvc         , use-cross: false , extension: .exe }
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install cross
        if: matrix.job.use-cross
        run: cargo install cross
      - name: Build
        run: |
          rustup update
          rustc -V
          rustup target add ${{ matrix.job.target }}
          if [ "${{ matrix.job.use-cross }}" == "true" ]; then
            cross build --release --target ${{ matrix.job.target }}
          else
            cargo build --release --target ${{ matrix.job.target }}
          fi
        shell: bash
      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.job.target }}/release/mogura{,-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}}
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.job.target }}/release/mogura-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
